name: myenv
channels:
  - pytorch
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  # --- KEY CHANGES ---
  # 1) Removed lines for conda, conda-libmamba-solver, conda-content-trust, conda-package-handling, etc.
  # 2) Removed libmamba, libmambapy, menuinst (these pinned the solver to Python >=3.12)
  # 3) Pinned Python to 3.10 to match PyTorch & other packages on Linux
  - python=3.10

  # --- Packages you still had pinned ---
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anaconda-anon-usage=0.5.0
  - archspec=0.2.3
  - blas=1.0
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.31
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - cpuonly=2.0
  - cryptography=43.0.3
  - distro=1.9.0
  - expat=2.6.4
  - faiss-cpu=1.9.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - fmt=9.1.0
  - freetype=2.12.1
  - frozendict=2.4.2
  - giflib=5.2.2
  - gmp=6.2.1
  - gnutls=3.6.15
  - icu=73.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.1
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libarchive=3.7.4
  - libcurl=8.9.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libfaiss=1.9.0
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libsolv=0.7.24
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.5
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.1
  - pcre2=10.42
  - pillow=11.0.0
  - pip=24.2
  - platformdirs=3.10.0
  - pluggy=1.5.0
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tqdm=4.66.5
  - truststore=0.8.0
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6

  # --- PIP Packages ---
  - pip:
      - google-genai==1.1.0
      - annotated-types==0.7.0
      - anthropic==0.42.0
      - anyio==4.8.0
      - cachetools==5.5.0
      - click==8.1.8
      - docstring-parser==0.16
      - fastapi==0.115.6
      - fsspec==2024.12.0
      - google-api-core==2.24.0
      - google-auth==2.37.0
      - google-cloud-aiplatform==1.76.0
      - google-cloud-bigquery==3.27.0
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.14.0
      - google-cloud-storage==2.19.0
      - google-crc32c==1.6.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.66.0
      - grpc-google-iam-v1==0.14.0
      - grpcio==1.69.0
      - grpcio-status==1.69.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.27.2
      - httpx-sse==0.4.0
      - huggingface-hub==0.27.1
      - jiter==0.8.2
      - langchain-core==0.3.29
      - langchain-google-vertexai==2.0.10
      - langsmith==0.2.10
      - orjson==3.10.14
      - proto-plus==1.25.0
      - protobuf==5.29.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - regex==2024.11.6
      - requests-toolbelt==1.0.0
      - rsa==4.9
      - safetensors==0.5.2
      - shapely==2.0.6
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.41.3
      - tenacity==9.0.0
      - tokenizers==0.21.0
      - transformers==4.48.0
      - uvicorn==0.34.0
      - openai==1.65.5